const bossDrops = {
    "Karnix": [
        "bow_aa_t5_boss_002_TraitExtract",
        "sword_a_t2_nomal_001_TraitExtract", 
        "chest_plate_aa_t1_nomal_004_TraitExtract",
        "hands_leather_aa_t2_set_001_TraitExtract",
        "ring_aa_t3_boss_002_TraitExtract",
        "head_plate_aa_t2_set_001_TraitExtract",
        "sword_a_t2_nomal_003_TraitExtract",
        "chest_plate_a_t2_set_002_TraitExtract",
        "bracelet_a_t2_addoption_001_TraitExtract",
        "head_plate_a_t2_set_001_TraitExtract",
        "hands_plate_a_t2_set_001_TraitExtract",
        "feet_plate_a_t1_nomal_003_TraitExtract",
        "legs_plate_a_t2_set_001_TraitExtract",
        "chest_plate_a_t2_set_001_TraitExtract",
        "ring_a_t1_nomal_001_TraitExtract"
    ],
    "Shaikal": [
        "wand_aa_t5_boss_003_TraitExtract",
        "bow_a_t2_nomal_004_TraitExtract",
        "feet_fabric_aa_t1_nomal_001_TraitExtract",
        "head_leather_aa_t2_set_001_TraitExtract",
        "ring_aa_t1_nomal_002_TraitExtract",
        "dagger_a_t2_nomal_003_TraitExtract",
        "feet_leather_a_t2_set_002_TraitExtract",
        "chest_leather_a_t1_nomal_001_TraitExtract",
        "head_leather_a_t2_set_001_TraitExtract",

        "hands_leather_a_t2_set_001_TraitExtract",
        "feet_leather_a_t2_set_001_TraitExtract",
        "legs_leather_a_t2_set_001_TraitExtract",
        "chest_leather_a_t2_set_001_TraitExtract",
        "ring_a_t2_addoption_001_TraitExtract",
    ],
    "Quimer-Rex": ["", ""],
    "Duque Magna": ["", ""],
    "Toublek": ["bow_aa_t3_mythicbeast_003_TraitExtract", "staff_a_t3_mythicbeast_003_TraitExtract"],
    "Lequirus": ["", ""]
}